#!/usr/bin/env bash

version=`ruby -r ./lib/southy/version.rb -e 'puts Southy::VERSION'`
dest=$1
ssh="ssh deploy@$dest"

rake build
scp pkg/southy-$version.gem deploy@$dest:
$ssh "sudo systemctl stop southy"
$ssh "gem list | grep southy && sudo gem uninstall southy"
$ssh "sudo gem install --no-ri --no-rdoc ./southy-$version.gem"
$ssh "sudo systemctl start southy"
$ssh "rm -f ./southy-$version.gem"
